# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: innocloud
# "service" is the name of this project. This will also be added to your AWS resource names.
service: push-notifications

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    DB_NAME: ${env:DB_NAME}
    COLLECTION_NAME: ${env:COLLECTION_NAME}
    ENVIRONMENT: lambda
functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"

